apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-blog
spec:
  selector:
    matchLabels:
      app: demo-blog
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-blog
    spec:
      containers:
      - name: demo-blog
        image: kotlin-k8s-demo:latest
        resources:
          limits:
            memory: 512Mi
            cpu: 1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
